#Needed for installation of azure provider, activated when i run terraform innit
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm" 
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.15.6"
}
# >= minimum version contraint

#Here I am configuring settings for this provider i.e. sub id, etc.
#Useful for when I need to deploy to 2 subs or more. To distinguish it, it needs an alias.

provider "azurerm" {
  features {}
  subscription_id = "899effae-fb98-4b70-a9b9-94321a00bcdf"
}
  provider "azurerm" {
  features {}
  alias           = "vpnproject"
  subscription_id = "408c57c0-9544-4c34-a2c4-4320359d01f1"
}

#Re: Module 1, experiments I did were:
#Initialising it, and seeing if autogenerated lockfile reflected it.
#Bumping version, again to see if lock file reflected it.

#Re the different providers. If I dont specify it, resources are deployed to first sub (default - cloud one).
#If I add a providers block to resource, it deploys to second/or whatever I add


